# Mini curso: Manejo y análisis de salidas del modelo numérico WRF usando Python
UAM Iztapalapa

Día 1: Notebook 1/2 

13 de diciembre de 2022
## Fundamentos de Python

Parte del material de este notebook está basado en la lección *Programming with Python* de los *Software Carpentry Workshops*, publicada bajo la licencia Creative Commons - Attribution License. Traducción y modificaciones por Karina Ramos Musalem. 

**Jupyter notebooks**

Los Jupyter notebooks son una aplicación web de código abierto que combinan celdas de código, figuras, ecuaciones y texto. Soportan varios lenguajes de programación como Python, R y Julia entre otros. Se abren en cualquier navegador (explorer, firefox, safari, chrome,...). Hay distintas maneras de usar los notebooks. Si n quieres instalar nada en tu computadora puedes usar Google Collab con cualquier cuenta de Gmail, como tu correo institutional.

Puedes cambiar el tipo de celda en la barra del encabezado seleccionando "code" para código y "markdown" para texto. Markdown es un lenguaje de marcado que tiene como objetivo facilitar la tarea de dar formato a un texto mediante el uso de solo caracteres. Aquí hay una [guía de uso en español](https://markdown.es/sintaxis-markdown/). Es muy común para escribir en internet y para tomar notas.

Si das doble click en esta celda de texto verás cómo se da formato al texto. Los encabezados se denotan con #, ##, ###, etc., texto en negritas entre doble asterisco, itálicas entre asteriscos, ...

Para ejecutar una celda da click en el botón Run en la barra de herramientas o puedes oprimir Shift+Enter. Esto último es lo más rápido, y con la práctica te acostubrarás a hacerlo en automático.

Algo importante que considedar es el orden en el que ejecutas las celdas. Después de ejecutar una célda de código aparece un número del lado izquierdo que indica el orden en el que has ejecutado las celdas. La primera celda ejecutada tiene un 1, la segunda 2 y así sucesivamente. Si vuelves a ejecutar una celda, el número cambiará. Esto tendrá más sentido una vez que empecemos.

## 1. Variables y asignación de variables

Preguntas a responder

    ¿Con qué tipos de datos básicos puedo trabajar en Python?
    ¿Cómo puedo crear variables en Python?
    ¿Puedo cambiar el nuevo valor de una variable creada previamente?

Objetivos

    Aprender a asignar un valor a una variable.

### 1.1 Variables

Cualquier intérprete de Python puede usarse como una calculadora (intérprete=jupyter notebook, python en la terminal, ipython, etc)


In [1]:
3 + 5 * 4

23

Esto está bien pero no es muy interesante. Para poder hacer algo útil con los datos debemos asignar su valor a una variable. En Python, asignamos un valor a una variable usando el signo de igual `=`. Por ejemplo, para asignar el valor 30 a la variable `peso_kg`, ejecutamos el comando:

In [2]:
peso_kg = 30



De ahora en adelante, cada vez que usemos `peso_kg`, Python sustituirá el valor que le asignamos. En otras palabras, una variable es un "nombre" para un valor (en verdad una variable es un "lugar" en la memoria de la computdora, pero esa es otra historia.)

En Python, los nombres de las variables:
* pueden incluir letras, digitos y guión bajo,
* no pueden empezar con un dígito,
* son sensibles a mayúsculas y minúsculas.

Por ejemplo:

`peso0` es un nombre válido pero `0peso` no lo es,
`peso` y `Peso` serán distintas variables.

### 1.2 Tipos de datos o variables

Python conoce distintos tipos de datos. Los tres más comúnes son:

* números enteros (integers),
* números decimales (floating point numbers) y
* cadenas (strings).

En el ejemplo anterior, la variable `peso_kg` contiene el valor entero`30`. Para crear una variable con valor decimal, podemos ejecutar:

In [3]:
peso_kg = 30.0

y para crear una cadena o *string* añadimos comillas dobles o simples alrededor de algún pedazo de texto:

In [4]:
peso_kg_texto = 'peso en kilogramos:'

Podemos usar la función `type` para ver de qué tipo es un valor datos. La función `type` funciona en variables también, pero recuerda que valor es que tiene el tipo, la variable solo es una etiqueta para el valor:

In [5]:
print(type(52))

<class 'int'>


In [6]:
taco = 'pastor'
print(type(taco))

<class 'str'>


El tipo de un valor determina que le puede hacer el programa:


In [7]:
print(5 - 3)


2


In [8]:
print('hello' - 'h')

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Los enteros y los decimales (floats) pueden mezclarse en operaciones aritméticas. Python 3 automáticamente convierte enteros a decimales cuando se requiere.



In [9]:
print(1 / 2.0)
print(3.0 ** 2)

0.5
9.0


### 1.3 Uso de las variables

Para mostrar el valor de una variable en la pantalla podemos usar la función `print`:

In [10]:
print(peso_kg)

30.0


Podemos mostrar varias cosas a la vez con un solo comando `print`:

In [11]:
print(peso_kg_texto, peso_kg)

peso en kilogramos: 30.0


Aún mejor, podemos hacer operaciones aritméticas entre variables dentro del comando print:

In [12]:
print('El peso en libras es:', 2.2 * peso_kg)

El peso en libras es: 66.0


Nota que el comando anterior NO cambió el valor de peso_kg:

In [13]:
print(peso_kg)

30.0


Para cambiar el valor de peso_kg, debemos asignarle un nuevo valor usando el signo igual `=`:

In [14]:
peso_kg = 65.0
print('El peso en kg ahora es:', peso_kg)

El peso en kg ahora es: 65.0


Asignar un valor a una variable no cambia el valor de otras variables. Por ejemplo, si creamos una variable `peso_lb` como:

In [15]:
peso_lb = 2.2 * peso_kg
print(peso_lb)

143.0


y después cambiamos el valor de peso_kg:

In [16]:
peso_kg = 80.0
print('peso_kg es: ', peso_kg, 'y peso_lb es: ', peso_lb)

peso_kg es:  80.0 y peso_lb es:  143.0


El valor de `peso_lb` no cambia. Esto es porque las variables no "recuerdan" de dónde viene su valor. Éste no se actualiza si cambiamos `peso_kg`.

#### Pon en práctica lo que aprendiste
1. ¿Qué valores tienen las variables `temperatura` y `salinidad` después de ejecutar los comandos mostrados en la siguente celda?
2. Comprueba tu respuesta ejecutando la celda siguiente y añadiendo el comando `print`con los **argumentos** necesarios para mostrar el valor de `temperatura`y `salinidad`. 

Nota: El **argumento** es la información que necesita el comando para ser ejecutado. Los argumentos son las variables o valores entre paréntesis después del comando. Por ejemplo, en `print('Hola mundo')`, el argumento del comando `print` es 'Hola mundo'.

In [17]:
temperatura = 20.5
salinidad = 50.2
temperatura = temperatura * 2.0
salinidad = salinidad - 20

In [18]:
# Añade el comando `print` en esta celda para desplegar el valor
# de las variables temperatura y salinidad. Después ejecuta la celda.

3. ¿Qué imprimirá el siguente progama?

Comprueba tu respuesta quitando los # (denotan comentario) y ejecutando la celda.

In [19]:
#primero, segundo = 'Marie', 'Tharp'
#tercero, cuarto = primero, segundo
#print(tercero, cuarto)

### 1.4 Índices y rebanadas
Podemos usar **índices** para aislar o seleccionar un solo caracter en una cadena.

Los caracteres en una cadena están ordenados. Por ejemplo, la cadena 'AB' no es igual a la cadena 'BA'. Gracias a este orden podemos tratar a una cadena como una lista de caracteres.

Cada posición en la cadena (primera, segunda, etc.) se identifica con un número entro llamado **índice**

Los índices **comienzan a partir de `0`** y se indican dentro de paréntesis cuadrados `[]`:

In [20]:
atomo = 'helio'
print(atomo[0])

h


Podemos seleccionar **rebanadas** o pedazos de una cadena formados por más de un caracter usando índices.

Python usa **listas**, que son conjuntos de elementos (Ej. enteros, decimales, cadenas, listas, etc.). Podemos tratar a una cadena como una lista de caracteres. 

Una **rebanada** o *slice* es una parte o subselección de elementos de una lista, como una cadena.

Podemos seleccionar una rebanada de una lista usando la notación `[inicio:final]` donde `inicio` es el índice del primer elemento que queremos seleccionar y `final` es el índice del elemento que está justo después del último elemento que queremos seleccionar.

Tomar una rebanada no modifica la lista original; en cambio, nos regresa una copia de parte de la lista original.

  


In [21]:
atomo = 'sodio'
print(atomo[0:3])

sod


#### Pon en práctica lo que aprendiste

Dada la siguente cadena:

`especie = "Acacia buxifolia"`

1. ¿Qué regresan las siguientes expresiones?:

    `especie[2:8]`
   
    `especie[11:] `
   
    `especie[:4]`
   
   `especie[:] `

    `especie[11:-3] `

    `especie[-5:-3]`

2. ¿Qué pasa cuando eliges un índice final que es más grande que la cantidad de elementos en la lista? (Ej. `especie[0:20]` o `especie[:103]`)



### 1.5 En resumen

* Las variables básicas de Python son de tipo entero (integer), decimal (floats) o cadenas (strings)
* Usa la función `type` para encontrar el tipo de un valor.
* El tipo controla qué operaciones podemos hacer con una variable.
* Usa `variable = valor` para asignar un valor a una variable y guardarlo en memoria.
* Las variables se crean conforme se requieren cuando se les asigna un valor.
* Usa `print(algo)` para mostrar o imprimir el valor de `algo`.
* Selecciona una rebanada de una lista usando los índices de los elementos que quieres usando la notación `lista[inicio:final]`.

## 2. Funciones nativas, ayuda y mensajes de error

### 2.1 Funciones

Ya hemos visto algunas funciones (Ej. print, type) - Ahora veamos con más cuidado como podemos "llamar" o ejecutar funciones.

El **argumento** es el valor que le pasamos a la función.

La función `len` nos dice la longitud de una cadena y toma exactamente un valor como argumento:


In [22]:
print(len('verde'))

5


`print` puede tomar 0 o 1 valores como argumento

In [23]:
print('antes')
print()
print('después')

antes

después


**Siempre debemos poner el paréntesis, aún si no hay argumento, para que Python entienda que estamos llamando a una función.**

Cada llamada a una función regresa "algo".

Si la función no regresa nada útil, regularmente regresa el valor especial `None`, que es un objeto de Python que funciona como comodín cuando no hay un valor.

In [24]:
resultado = print('ejemplo')
print('El resultado de la función print es', resultado)

ejemplo
El resultado de la función print es None


Las funciones pueden tener valores por default para algunos argumentos. Por ejemplo, la función `round` redondea un decimal. Pero si no especificamos a cuántos dígitos queremos redondear, el valor por omisión es redondear a 0 decimales:

In [25]:
round(3.712)

4

En cambio, podemos especificar el número de decimales si pasamos un valor para el segundo argumento:

In [26]:
round(3.712, 1)

3.7

#### Pon en práctica lo que aprendiste

Si Python empieza a contar desde 0, y la función `len` regresa el número de caracteres en una cadena, ¿cómo podemos imprimir el último caracter de una cadena arbitraria usando índices y la función `len`?

In [27]:
# Programa tu solución aquí

### 2.2 Métodos
Las funciones pueden tomar otra forma, que aparecerá en secciones más adelante. Cuando una función está atada a un objeto se le concoe como un **método**. Los métodos tienen paréntesis, como las funciones, pero se colocan después de la variable a la que queremos aplicarle el método o función.

Algunos métodos se usan para operaciones internas de Python y se denotan con doble guión bajo.

In [28]:
mi_cadena = 'Hola Mundo!'   # creación de un objeto cadena  

print(len(mi_cadena))       # la función len toma una cadena como argumento y regresa la longitud de la cadena

print(mi_cadena.swapcase()) # Llamando al método swapcase sobre el objeto mi_cadena

print(mi_cadena.__len__())  # Llamando al método interno  __len__ sobre mi_cadena

11
hOLA mUNDO!
11


¡Puede ser que los veas seguidos! Operan de izquierda a derecha:
 


In [29]:
print(mi_cadena.isupper())         # No todas las letras son mayúsculas

print(mi_cadena.upper())           # Esto cambia todas las letras a mayúsculas

print(mi_cadena.upper().isupper()) # Ahora todas las letras son mayúsculas

False
HOLA MUNDO!
True


### 2.3 Ayuda 
Usa la función `help` para obtener información acerca del uso de una función. Todas las funciones nativas tienen documentación en línea.


In [30]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



En los notebooks de Jupyter hay dos maneras de obtener ayuda. 

1. Coloca el cursor cerca de donde llamas a la función en una celda y oprime Shift + tab.

2. Teclea el nombre de la función en una celda con un signo de interrogación al final y corre la celda

In [31]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method


### 2.4 Mensajes de error

Python reporta un **error de sintaxis** cuando no puede entender la fuente de un programa o cuando no usamos la sintaxis correcta para llamarlo. Ni siquiera intentará correr el programa si no lo entiende.


In [32]:
# Olvidé cerrar las comillas al definir la cadena
name = 'Feng

SyntaxError: EOL while scanning string literal (<ipython-input-32-b47fdb3bdb6d>, line 2)

In [33]:
# Un '=' extra  en la asiganción
edad = = 53

SyntaxError: invalid syntax (<ipython-input-33-c8bf44ee6a52>, line 2)

Analicemos el mensaje de error:

In [34]:
print("hello world"

SyntaxError: unexpected EOF while parsing (<ipython-input-34-fe69f65f3ba9>, line 1)


El mensaje indica que hay un problema en la primera línea del input (line 1)
        
En este caso la sección "<ipython-input-"  nos dice que estamos trabajando con input en Ipython, el intérprete de Python que usa el Jupyter notebook. 

La parte -34- indica que el error es en la celda 34.

Después viene la línea problemática del código, que indica el problema en el código con un ^.

Python reporta un **error de runtime** cuando algo sale mal mientras el programa se ejecuta y un **error de nombre** cuendo llamamos a una variable que no está definida:

In [35]:
edad = 52
remaining = 100 - egdad # 'edad' está mal escrito

NameError: name 'egdad' is not defined

La página ofical de [documentación de Python](https://docs.python.org/es/3/index.html) es la fuente más completa de información acerca del lenguaje. Está **disponible en distintos idiomas** y tiene muchos recursos disponibles. La sección de [funciones nativas](https://docs.python.org/es/3/library/functions.html) contiene un catálogo de todas las funciones, incuidas las que vimos en esta sección.


### 3. La biblioteca `numpy`

Usamos la biblioteca [NumPy](https://numpy.org/), llamada así por *Numerical Python*, cuando queremos hacer operaciones sofisticadas (y no tanto) con muchos números, especialmente si tenemos matrices o arreglos. Para decirle a Python que queremos empezar a usar NumPy debemos **importar** NumPy:

In [37]:
import numpy

Importar una biblioteca es como sacar un instrumento de laboratorio de la bodega para tenerlo a la mano. Las bibliotecas nos permiten usar funciones adicionales a las del paquete básico de Python. Así como en el laboratorio, importar demasiadas bibliotecas puede complicar o frenar tus programas -- así que solo importa lo que necesites.

Una vez que importamos la biblioteca numpy podemos pedirle que lea nuestro archivo de datos:

In [40]:
numpy.loadtxt(fname='datos/precip_mensual_estacion01.csv', delimiter=',')

array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.173, 0.021,
        0.035, 0.014, 0.   ],
       [0.005, 0.021, 0.026, 0.001, 0.003, 0.079, 0.113, 0.084, 0.064,
        0.012, 0.007, 0.   ],
       [0.   , 0.001, 0.001, 0.014, 0.032, 0.069, 0.069, 0.115, 0.135,
        0.071, 0.033, 0.   ],
       [0.001, 0.006, 0.005, 0.015, 0.068, 0.085, 0.061, 0.078, 0.07 ,
        0.067, 0.006, 0.015],
       [0.   , 0.003, 0.   , 0.009, 0.103, 0.063, 0.03 , 0.068, 0.098,
        0.009, 0.001, 0.   ],
       [0.005, 0.   , 0.013, 0.009, 0.028, 0.06 , 0.092, 0.076, 0.081,
        0.01 , 0.042, 0.   ],
       [0.   , 0.   , 0.012, 0.016, 0.048, 0.085, 0.165, 0.126, 0.126,
        0.   , 0.   , 0.   ],
       [0.008, 0.001, 0.008, 0.02 , 0.024, 0.059, 0.063, 0.107, 0.065,
        0.046, 0.012, 0.   ]])

El comando `numpy.loadtxt(...)` es un llamado que le pide a Python que ejecute la función `loadtxt`que pertenece a la biblioteca `numpy`. Esta notación se usa en todo Python: la cosa que aparce después del punto está contenida en la cosa antes del punto.

`numpy.loadtxt` tiene dos **parámetros** o **argumentos**: el numbre del archivo que vamos a leer y el *delimiter* que nos dice cuál es el caracter que separa los valores en cada línea. Ambos parámtros deben ser tipo *string*, por lo que los rodeamos con comillas.

Como no le hemos dicho a Python que haga algo con el output o resultado de la función, el notebook imprime los datos por default. Solo muestra algunas líneas y columnas (usa `...` para omitir algunos elementos cuando el arreglo es muy grande). Para ahorrar espacio, python no muestra los ceros después del punto decimal (1. en vez de 1.0).

#### **Nota: Atajo para importación de bibliotecas** 

En esta clase usamos la sintaxis `import numpy` para importar NumPy. Después llamamos a las funciones dentro de numpy como `numpy.función`. Es posible utilizar un nombre mas corto para numpy usando la sintáxis `import numpy as np`. Así, llamamos a las funciones dentro de numpy como `np.función`. Esta es una práctica común, y resulta en líneas de código más cortas, especialmente si el nombre de la biblioteca es muy largo. Puedes usar la sintáxis que prefieras pero ten cuidado de usar nombres cortos que sean descriptivos y tengan sentido para otros. Es decir, no abrevies `numpy `como `n`, eso puede ser confuso.

Volviendo a los datos, nuestra ejecución de `numpy.loadtxt` leyó los datos pero no los guardó en memoria. Para ello debemos asignar el arreglo de datos a una variable. Ejecutemos de nuevo `numpy.loadtxt` asignando los datos a una variable:

In [41]:
data = numpy.loadtxt(fname='datos/precip_mensual_estacion01.csv', delimiter=',')

Esto no produce ningún output porque asignamos el output a la variable `data`. Para corroborar que se guardaron los datos, imprimimos el valor de la variable `data`:

In [42]:
print(data)

[[0.    0.    0.    0.    0.    0.    0.    0.173 0.021 0.035 0.014 0.   ]
 [0.005 0.021 0.026 0.001 0.003 0.079 0.113 0.084 0.064 0.012 0.007 0.   ]
 [0.    0.001 0.001 0.014 0.032 0.069 0.069 0.115 0.135 0.071 0.033 0.   ]
 [0.001 0.006 0.005 0.015 0.068 0.085 0.061 0.078 0.07  0.067 0.006 0.015]
 [0.    0.003 0.    0.009 0.103 0.063 0.03  0.068 0.098 0.009 0.001 0.   ]
 [0.005 0.    0.013 0.009 0.028 0.06  0.092 0.076 0.081 0.01  0.042 0.   ]
 [0.    0.    0.012 0.016 0.048 0.085 0.165 0.126 0.126 0.    0.    0.   ]
 [0.008 0.001 0.008 0.02  0.024 0.059 0.063 0.107 0.065 0.046 0.012 0.   ]]


Ahora que tenemos los datos en memoria, podemos manipularlos. Primero, preguntemos qué **tipo** de cosa es `data`:

In [43]:
print(type(data))

<class 'numpy.ndarray'>


El output nos dice que `data`es un arreglo de numpy N-dimensional. 

Los datos corresponden a la precipitación anual en la estación Meteorológica [PEMBU](https://www.ruoa.unam.mx/pembu/) del Instituto de Ciencias de la Atmósfera y Cambio Climático de la UNAM ([ICAyCC](https://www.atmosfera.unam.mx/)). Las filas de este arreglo correponden a distintos años (2011-2018) y las columnas a la precipitación promedio por mes del año. La precipitación está medida en milímetros de lluvia. 

NOTA: Un arrelgo de NumPy contiene uno o más elementos del mismo tipo. La función `type` solo nos dice que la variable `data` es un arreglo de NumPy pero no te dice el tipo de las cosas dentro del arreglo. Podemos conocer el tipo de los datos contenidos en `data` utilizando:

In [44]:
print(data.dtype)

float64


Esto nos dice que los elementos del arreglo de NumPy `data` son de tipo decimal o `float`.

Con el siguiente comando podemos conocer la forma o tamaño del arreglo:

In [46]:
print(data.shape)

(8, 12)


Esto nos dice que el arreglo `data` contiene 8 filas y 12 columnas. Hemos creado la variable `data` para guardar la información de la precipitación mensual, pero no solo creamos eso; también creamos automáticamente información acerca del arreglo llamada miembros o atributos. Esta información adicional describe a `data`de la misma forma que un adjetivo describe a un sustantivo. `data.shape`es un atributo de data que describe las dimensiones de `data`. Usamos la misma notación de punto para los atributos de variables que para las funciones en bibliotecas porque tienen la misma relación todo-parte.

Como vimos antes para cadenas y listas, si queremos seleccionar o sacar un solo número del arreglo, debemos proporcionar un índice entre paréntesis cuadrados `[]` después del nombre de la variable. Nuestros datos de precipitación tienen dos dimensiones, por lo que debemos porporcionar dos índices para referirnos a un valor específico:

In [47]:
print('el primer elemento en data es:', data[0,0])

el primer elemento en data es: 0.0


In [48]:
print('el elemento en la mitad de data es:', data[4,6])

el elemento en la mitad de data es: 0.03


Usamos `data[0,0]`para elegir el elemento en la primera columna primer renglón. Los lenguajes de programación como Fortran, Matlab y R empiezan a contar desde 1 porque eso hacen los humanos. Los lenguajes en la familia C (como C++, Java, Perl y Python) cuentan desde 0 porque eso representa el incremento desde el primer valor en el arreglo (el segundo valor está desplazado por un índice desde el primer valor). Esto es más cercano a la forma en que las computadoras repesentan arreglos (Aqui hay una [entrada del blog de Mike Hoye](http://exple.tive.org/blarg/2013/10/22/citation-needed/) si les interesa saber más sobre esto).

Como resultado, si tenemos un arreglo de MxN en Python, sus índices van del 0 a M-1 en la primera dimensión y de 0 a N-1 en la segunda. Lleva un rato acostumbrarse, pero pueden pensar que la regla es que el índice es el número de pasos tenemos que saltar desde el comienzo hasta el elemento que queremos.

<img src="imagenes/indices.svg">

Otra nota al respecto. Python muestra el elemento con índices `[0,0]`en el extremo superior izquierdo. Esto es consistente con la forma en que dibujamos matrices en matemáticas, pero distinto a las coordenadas Cartesianas. **Los índices son (fila, columna)**.

### 2.2 Seleccionar porciones o "rebanadas" de datos

Usando índices como `[3,8]` seleccionamos un solo elemento del arreglo, pero podemos seleccionar secciones o rebanadas (*slice* en inglés) también. Por ejemplo, podemos seleccionar los primeros 5 meses de datos (columnas) de los primeros 4 años (filas): 

In [49]:
print(data[0:4, 0:5])

[[0.    0.    0.    0.    0.   ]
 [0.005 0.021 0.026 0.001 0.003]
 [0.    0.001 0.001 0.014 0.032]
 [0.001 0.006 0.005 0.015 0.068]]


La selección o rebanada `0:4` quiere decir "Empieza en el índice 0 y selecciona hasta, pero **sin incluir**, el índice 4". De nuevo, lleva un poco de tiempo acostumbrarse a este "hasta, pero no incluyas", pero la regla es que la diferencia entre los límites inferior y superior es el número de valores en la rebanada.

Las rebanadas no tienen que empezar en 0:

In [52]:
print(data[5:8, 1:9])

[[0.    0.013 0.009 0.028 0.06  0.092 0.076 0.081]
 [0.    0.012 0.016 0.048 0.085 0.165 0.126 0.126]
 [0.001 0.008 0.02  0.024 0.059 0.063 0.107 0.065]]


Además, no es necesario incluir los límites superior e inferior de la selección. Si no incluimos límite inferior, Python usa el 0 como default; si no incluimos el superior, Python selecciona hasta el último elemento de ese eje; si no especificamos ningún límite (`:`), Python selecciona todo el eje:

In [53]:
rebanada = data[:3, 8:]
print('la rebanada es:')
print(rebanada)

la rebanada es:
[[0.021 0.035 0.014 0.   ]
 [0.064 0.012 0.007 0.   ]
 [0.135 0.071 0.033 0.   ]]


El ejemplo anterior selecciona las filas 0 a 2 y las columnas 8 al final del arreglo.

### 2.3 Analizar los datos

NumPy tiene muchas funciones útiles que toman al arreglo como input para realizar alguna operación con sus valores. Si queremos encontrar el promedio anual de precipitación usando todos los años, le podemos pedir a NumPy que compute el promedio de `data`:

In [54]:
print(numpy.mean(data))

0.036104166666666666


`mean` (*mean* es promedio en inglés) es una función que toma un arreglo como argumento.  

De vuelta a los datos, usemos otras tres funciones para obtener algunos valores descriptivos de la precipitación. Además usaremos la asignación múltiple, que es una forma conveniente de asignar varios valores en una línea de código:

In [55]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('precipitación máxima (mm):', maxval)
print('precipitación mínima (mm):', minval)
print('desviación estandar (mm):', stdval)

precipitación máxima (mm): 0.173
precipitación mínima (mm): 0.0
desviación estandar (mm): 0.0421644793157964


Aquí asignamos el output de `numpy.max(data)` a la variable `maxval`, el valor de `numpy.min(data)` a la variable `minval`, etc.

#### TIP: 
Si estas trabajando en un *notebook* puedes ver las funciones dentro de una biblioteca escribiendo el `nombre-de-la-biblioteca.` y despues `Tab` (la tecla tab). Por ejemplo, escribe `numpy.` y la tecla tab para ver todas  las funciones dentro de numpy.

Cuando analizamos datos, frecuentemente queremos analizar variaciones en datos estadísticos, como la precipitación mensual máxima por año o la precipitación promedio en todos los meses de mayo. Una forma de hacer esto es crear un nuevo arreglo temporal de datos y después calcular sobre ese arreglo:  

In [56]:
anio_2010 = data[0, :] # 0 en el primer eje (filas), y todo en el segundo eje (columnas)print('maximum inflammation for patient 0:', numpy.max(patient_0))
print('La precipitación mensual máxima (mm) en 2010 fue:', numpy.max(anio_2010))

La precipitación mensual máxima (mm) en 2010 fue: 0.173


En verdad no necesitamos guardar la fila seleccionada en una variable. Podemos combinar la selección con el llamado a la función en una sola línea:

In [57]:
print('La precipitación mensual máxima (mm) en 2010 fue:', numpy.max(data[0,:]))

La precipitación mensual máxima (mm) en 2010 fue: 0.173


Imagina que necesitamos la máxima precipitación en cada año (diagrama de la izquierda) o el promedio de precipitación por cada mes (derecha). Como se muestra en el diagrama, queremos realizar operaciones a lo largo de los ejes:

<img src="imagenes/python-operations-across-axes.png">

La mayoría de las funciones que usan arreglos como input nos permiten especificar a lo largo de qué eje queremos hacer la operación. Si pedimos el promedio sobre el eje 0 (filas en nuestro ejemplo 2D), tenemos:

In [58]:
print(numpy.mean(data, axis=0))

[0.002375 0.004    0.008125 0.0105   0.03825  0.0625   0.074125 0.103375
 0.0825   0.03125  0.014375 0.001875]


Podemos checar rápidamente cuáles son las dimensiones del output:

In [60]:
print(numpy.mean(data, axis=0).shape)

(12,)


La expresión `(12,)`nos dice que tenemos un vector de 12x1, así que esto es la precipitación promedio por mes (el promedio de precipitación para toodos los eneros, febreros, etc).

Si tomamos el promedio sobre el eje 1 (columnas), obtenemos:

In [61]:
print(numpy.mean(data, axis=1))

[0.02025    0.03458333 0.045      0.03975    0.032      0.03466667
 0.04816667 0.03441667]


Que es la precipitación promedio para cada año.

### Pon en práctica lo que aprendiste
Los arreglos se pueden apilar (*stack* en inglés) uno sobre otro usando las funciones de NumPy `vstack`y `hstack` para apliar en la vertical y horizontal, respectivamente.

In [62]:
A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


Escribe código adicional que rebane la primera y última columna de `A`, y las apile en un arreglo de dimensiones 2x3. Usa el comando `print`para que puedas verificar tu solución.

In [ ]:
# Programa tu solución aquí